// Mazo uruguayizado de "Cartas contra la Humanidad".
// Cartas negras: { t: "texto con ___", pick: cuántas blancas se juegan }
// Cartas blancas: strings.

export const BLACK = [
  { t: "Regresa Pasión de Carnaval, ¡con ___ y ___ de anfitriones!", pick: 2 },
  { t: "La AUF acuerda dejar libre a Suárez a cambio de ___.", pick: 1 },
  { t: "Natalia Oreiro, en su lecho de muerte, pidió que la enterraran junto a ___.", pick: 1 },
  { t: "Espacio Político Pagado: Salle hablará sobre su proyecto de ley de ___.", pick: 1 },
  { t: "Este año voy a Minas para pedirle a la Virgen del Verdún por ___.", pick: 1 },
  { t: "Del viejo bar Fun Fun, media cuadra al sur. Ahí enfrente vas a ver ___.", pick: 1 },
  { t: "Orientales, la patria o la tumba, ___ nos da.", pick: 1 },
  { t: "Mitad carpincho, mitad termo: la biografía no autorizada de ___.", pick: 1 },
  { t: "¡Soy el intendente de Montevideo, si yo quiero ___, así será!", pick: 1 },
  { t: "Un retrato al óleo de ___ en el Salón de los Pasos Perdidos.", pick: 1 },
  { t: "___: Sólo en Barraca Europa a 40 cuotas.", pick: 1 },
  { t: "No tengo recibo de sueldo pero tengo ___.", pick: 1 },
  { t: "Tienda Inglesa te trae el álbum de ___. ¡Son 100 diferentes!", pick: 1 },
  { t: "Un alfajor, un colet y me da lo que sobra en ___.", pick: 1 },
  { t: "___ provoca trancadera de 2 horas en la Interbalnearia. Estaremos reportando.", pick: 1 },
  { t: "“___”, declarado de lectura obligatoria por ANEP.", pick: 1 },
  { t: "El Museo Nacional de Artes Visuales presenta su nueva exhibición: “___: Una mirada introspectiva.”", pick: 1 },
  { t: "Como la vez que amanecí en el baño de Jackson con ___ encima.", pick: 1 },
  { t: "MSP declara obligatoria la vacuna contra ___.", pick: 1 },
  { t: "Describa en una palabra la gestión de Lacalle Pou.", pick: 1 },
  { t: "Sólo es hombre el que tiene derechos, no el que vive de ___.", pick: 1 },
  { t: "Devoto se puso las pilas y sacó una versión de ___.", pick: 1 },
  { t: "Un reality de Canal 10 sobre 6 celebridades atrapadas en una casa con ___.", pick: 1 },
  { t: "Socio Espectacular presenta a su nuevo integrante: ___.", pick: 1 },
  { t: "Antel, ¿cómo se dice ___ en portuñol?", pick: 1 },
  { t: "Prefiero morir en el calabozo sexual de Graciela Bianchi antes que ___.", pick: 1 },
  { t: "Es el equivalente de Tabárez pero de ___.", pick: 1 },
  { t: "Comprar: • Yerba • Bizcochos • Colet • ___", pick: 1 },
  { t: "Agárrense de las manos, unos a otros con ___.", pick: 1 },
  { t: "Trocitos de ___ cubiertos de chocolate Ricard. ¡Los argentinos lo aman!", pick: 1 },
  { t: "Nuevos palitos de queso. Ahora con sabor natural a ___.", pick: 1 },
  { t: "Le dejo todo mi dinero a la Teletón. Pero a vos te dejo lo más importante: ___.", pick: 1 },
  { t: "Taxistas bloquean 18 de Julio para exigir que les otorguen derecho a ___.", pick: 1 },
  { t: "Última hora: Cierran el único cine de Atlántida para darle espacio a ___.", pick: 1 },
  { t: "Solicitan quitar la estatua de Rivera y cambiarla por un monumento a ___.", pick: 1 },
  { t: "Punta del Este + drogas + andar caliente = ___.", pick: 1 },
  { t: "Vení a ___. ¿O te cagás, loca?", pick: 1 },
  { t: "¿Cuál fue la agenda oculta del gobierno del Frente Amplio?", pick: 1 },
  { t: "Nuevo ajuste fiscal propone meterle IVA de 25% a ___. ¡Ya fue!", pick: 1 },
  { t: "La Cumparsita fue inspirada en la tradición montevideana de ___.", pick: 1 },
  { t: "¿Cuál es el vicio secreto de Batman?", pick: 1 },
  { t: "¿Qué me llevaría en un viaje al pasado para convencer a la gente de que soy del futuro?", pick: 1 },
  { t: "¿Cuál es mi anti droga?", pick: 1 },
  { t: "La AUF ha prohibido ___ por dar a los jugadores una ventaja injusta.", pick: 1 },
  { t: "Una manera para superar cualquier pandemia es ___ .", pick: 1 },
  { t: "Así es, yo maté a ___. ¿Que cómo lo hice? ___.", pick: 2 },
  { t: "Y el premio Iris por ___ es para ___.", pick: 2 },
  { t: "Los estudios demuestran que las ratas de laboratorio resuelven laberintos un 50% más rápido tras ser expuestas a ___.", pick: 1 },
  { t: "A los chetos de Carrasco les gusta ___.", pick: 1 },
  { t: "___: probado en gurises, aprobado por las madres.", pick: 1 },
  { t: "¿Qué mejora con los años?", pick: 1 },
  { t: "Lo siento, acabo de ___.", pick: 1 },
  { t: "La excursión al campo fue completamente arruinada por ___.", pick: 1 },
  { t: "Antes de matarte, señor Bond, me gustaría mostrarte ___.", pick: 1 },
  { t: "Una novela apocalíptica que retrata la vida en Uruguay después de ___.", pick: 1 },
  { t: "Desde el incidente, ya La Teja no huele a bizcochos, ahora huele a ___.", pick: 1 },
  { t: "Las piedras de la rambla en realidad eran representaciones charrúas de ___.", pick: 1 },
  { t: "___ + ___: Un poema canario.", pick: 2 },
  { t: "Quiero asaltar tu ___ y navegar en tu ___.", pick: 2 },
  { t: "Datos de una encuesta de Equipos revelaron que un 75% de los uruguayos suelen ser ___.", pick: 1 },
  { t: "No es que ___ tenga algo malo, sino que voses no lo entienden.", pick: 1 },
  { t: "Tengo una condición: que en vez de menstruación, mi cuerpo bota ___.", pick: 1 },
  { t: "Tengo una condición que sólo me excito con ___.", pick: 1 },
  { t: "Alexa: Notifícame cuando llegue ___.", pick: 1 },
  { t: "El lóbulo parietal, esa parte del cerebro que sirve para procesar ___.", pick: 1 },
  { t: "La gente votó por los nazis y le gusta ___. §No se puede confiar en la gente!", pick: 1 },
  { t: "Más vale pájaro en mano que ___.", pick: 1 },
  { t: "Dame ritmo, dame sabor, dame ___.", pick: 1 },
  { t: "No es acoso sexual, es ___.", pick: 1 },
  { t: "Hay 3 tipos de dengue: el 1, el 2 y el ___.", pick: 1 },
  { t: "El fallecido tenía 3 disparos en la cara y una nota que decía: “___”.", pick: 1 },
  { t: "Antes era ___, ahora le llamamos arte conceptual.", pick: 1 },
  { t: "“Éxitos que fueron de uno, y ahora son de ___”.", pick: 1 },
  { t: "¿Qué traigo en mi bolso misterioso que no he soltado en toda la noche?", pick: 1 },
  { t: "No me gusta el chisme, pero el último que fue al baño dejó ___.", pick: 1 },
  { t: "No soy machista, pero las mujeres deberían limitarse a ___.", pick: 1 },
  { t: "Descríbame en una palabra.", pick: 1 },
  { t: "Deme por favor un entero de cantonés con ___.", pick: 1 },
  { t: "No es sorpresa Desde niño sabía que me casaría con ___.", pick: 1 },
  { t: "Me soñé con vos. Estábamos en la cama a punto de ___.", pick: 1 },
  { t: "En su última sesión, la CIDH ha decidido agregar ___ como nuevo derecho humano.", pick: 1 },
  { t: "Las gente vieja huele a ___.", pick: 1 },
  { t: "Una verdad absoluta es ___.", pick: 1 },
  { t: "Solo un verdadero hombre puede ___.", pick: 1 },
  { t: "Comenzaré a hacer deporte en cuanto ___ sea considerado como tal.", pick: 1 },
  { t: "Un test en línea me dijo que soy ___.", pick: 1 },
  { t: "¿Por qué los hombres me envían fotos en internet de ___?", pick: 1 },
  { t: "¦Necesitas una cuerda para ___?", pick: 1 },
  { t: "¿Cuál es el secreto para ganar los juegos del hambre?", pick: 1 },
  { t: "¿Qué es divertido hasta que se vuelve raro?", pick: 1 },
  { t: "Solo hay 2 cosas seguras en la vida: La muerte y ___.", pick: 1 },
  { t: "Bebo para olvidar ___.", pick: 1 },
  { t: "A la izquierda le preocupa ___.", pick: 1 },
  { t: "Nadie JYLLYxH que soy alérgico a ___.", pick: 1 },
  { t: "¿Qué hay realmente al final del arcoiris?", pick: 1 },
  { t: "Solo es cuestión de tiempo para tener un presidente que ___.", pick: 1 },
  { t: "___, nueva temporada. Ahora en Netflix", pick: 1 },
  { t: "Ya no somos novios. Después de ___ya nada fue igual.", pick: 1 },
  { t: "___, gran pilar de nuestra sociedad moderna.", pick: 1 },
  { t: "___, nuestra única arma contra el terrorismo.", pick: 1 },
  { t: "¡Es un milagro! Una mancha en mi tostada con forma de ___.", pick: 1 },
  { t: "Te dejo todos mis terrenos hijo mío, pero tienes que prometerme que dejarás de ___.", pick: 1 },
  { t: "¿Eso es ___ en tu bolsillo o sólo estás feliz de verme?", pick: 1 },
  { t: "Para no perder la tradición navideña, este año mis papás me volvieron a regalar ___.", pick: 1 },
  { t: "Estoy viviendo el sueño. ¡Me pagan por ___!", pick: 1 },
  { t: "Morí por unos minutos y fui al cielo. Me sorprendió que me recibiera ___.", pick: 1 },
  { t: "Mi plan es irme a la frontera a comprar ___ al por mayor.", pick: 1 },
  { t: "___ es mi mayor motivación para ir al Gym.", pick: 1 },
  { t: "No hay primera cita perfecta sin ___.", pick: 1 },
  { t: "___ te ha enviado una solicitud de amistad.", pick: 1 },
  { t: "¡Mírenla! Mírenla como poco a poco se convierte en ___.", pick: 1 },
  { t: "Hice mi fortuna creando un app para encontrar ___.", pick: 1 },
  { t: "¿Papá, por qué mamá está llorando?", pick: 1 },
  { t: "Mi plan para dominar el mundo inicia con ___.", pick: 1 },
  { t: "¿Qué es ese olor?", pick: 1 },
  { t: "¿Que ha estado haciendo difícil la vida en la colonia nudista de Rocha?", pick: 1 },
  { t: "___: Bueno hasta la última gota!", pick: 1 },
  { t: "Durante el sexo me gusta pensar en ___.", pick: 1 },
  { t: "La medicina alternativa ahora usa las propiedades curativas de ___.", pick: 1 },
  { t: "Querido diario: Hoy entré a la casa de una joven pareja y entre los tres nos pusimos a ___.", pick: 1 },
  { t: "Por culpa de un error de Marketing, Tienda Inglesa ha dejado de vender ___.", pick: 1 },
  { t: "¿Por qué estoy pegajoso?", pick: 1 },
  { t: "¿Qué ayuda a Putin a relajarse?", pick: 1 },
  { t: "El peor temor de una feminista es: ___.", pick: 1 },
  { t: "___, ¡A que no puedes comer sólo uno!", pick: 1 },
  { t: "Durante el comúnmente infravalorado Periodo Marrón de Picasso, él hizo cientos de pinturas de ___.", pick: 1 },
  { t: "La guerra sirve para ___.", pick: 1 },
  { t: "¿Qué es lo que no te gustaría encontrar en un plato de comida china?", pick: 1 },
  { t: "¿Cuál es el próximo juguete de la Cajita Feliz?", pick: 1 },
  { t: "Este año, en vez de carbón, Papá Noel traerá ___ a los niños malos.", pick: 1 },
  { t: "¿Cómo mantengo estable mi relación de pareja?", pick: 1 },
  { t: "Cuando sea presidente de Uruguay, crearé el ministerio de ___.", pick: 1 },
  { t: "¿Cuál es mi poder secreto?", pick: 1 },
  { t: "Estados Unidos ha empezado a enviar ___ a los niños de Ucrania.", pick: 1 },
  { t: "Ojalá no hubiese perdido el manual de ___.", pick: 1 },
  { t: "¿Por qué no puedo dormir por las noches?", pick: 1 },
  { t: "Cuando esté en la cárcel, meteré ___ de contrabando.", pick: 1 },
  { t: "El paraíso está lleno de ___.", pick: 1 },
  { t: "¿Qué es lo que hay que hacer para llevarte a la cama?", pick: 1 },
  { t: "Cuando sea millonario, levantaré una estatua de Kia en conmemoración de ___.", pick: 1 },
  { t: "¿Por qué no puedo dormir en la noches?", pick: 1 },
  { t: "Tengo problemas pero ___ no es uno de ellos.", pick: 1 },
  { t: "No soy doctor pero estoy seguro de que lo que te hace sufrir se llama ___.", pick: 1 },
  { t: "¿Cuál es el mejor amigo de una chica?", pick: 1 },
  { t: "Durante su crisis de la edad mediana, mi papá realmente se involucró con ___.", pick: 1 },
  { t: "¿Qué me han estado ocultando mis padres?", pick: 1 },
  { t: "¿Qué fue lo que dejó esa mancha en mi sillón?", pick: 1 },
  { t: "Yo nunca entendí verdaderamente ___ hasta que encontré ___.", pick: 2 },
  { t: "¿Qué fue lo que hizo que mi primer beso fuera tan raro?", pick: 1 },
  { t: "El secreto para un matrimonio duradero es la comunicación... la comunicación y ___.", pick: 1 },
  { t: "La ciencia nunca explicará ___.", pick: 1 },
  { t: "¿Pero qué fue lo que trajiste para mostrarnos y decirnos?", pick: 1 },
  { t: "¿Tienes problemas con ___? Intenta con ___.", pick: 2 },
  { t: "El proceso de sanidad inició cuando me uní a un grupo para víctimas de ___.", pick: 1 },
  { t: "¿Qué me produce gases de manera incontrolable?", pick: 1 },
  { t: "Aprendí de la manera dura que puedes animar a un amigo en duelo con: ___.", pick: 1 },
  { t: "___. ¡It’s a trap!", pick: 1 },
  { t: "La cita a ciegas era un desastre hasta que descubrímos intereses en común en ___.", pick: 1 },
  { t: "¿Por qué me duele todo?", pick: 1 },
  { t: "¿Qué encuentra mi abuela perturbador aunque extrañamente encantador?", pick: 1 },
  { t: "Usaré mi único viaje en el tiempo para experimentar ___.", pick: 1 },
  { t: "Vos, yo, y ___. Pensalo.", pick: 1 },
  { t: "Ya casi llegamos, hijo. Sólo nos falta ___.", pick: 1 },
  { t: "Pero señor Juez, matar no es un crimen cuando ___ está en juego.", pick: 1 },
  { t: "Ahora que Netflix compró sus derechos, por fin podremos ver un refrito de ___.", pick: 1 },
  { t: "No es coincidencia: Su mamá + ___ = vos.", pick: 1 },
  { t: "¡Qué curioso que lo menciona! Yo también vengo de donar ___.", pick: 1 },
  { t: "Orquesta Filarmónica presenta: “Días de Gloria: Un Tributo a ___”.", pick: 1 },
  { t: "___ te ha enviado ___ por WeTransfer. Hacé clic acá para descargar.", pick: 2 },
  { t: "Los gringos tienen a Sinatra, nosotros tenemos a ___.", pick: 1 },
  { t: "El hombre hace, el mono imita, pero con ___ no hay quien compita.", pick: 1 },
  { t: "Querido diario, perdóname por tenerte abandonado, pero tenía que ___.", pick: 1 },
  { t: "Mamá, papá: Lo que siempre sospecharon era cierto: Soy ___.", pick: 1 },
  { t: "Las peores secuelas que me quedaron de la vacuna son ___ y ___.", pick: 2 },
  { t: "En mi próximo truco sacaré ___ de ___.", pick: 2 },
  { t: "¿Las trompetas del apocalipsis? Son algo así como ___ + ___.", pick: 2 },
  { t: "History Chanel presenta ___: La historia de ___.", pick: 2 },
  { t: "Con tiempo y presión suficientes, ___ se transformará en ___.", pick: 2 },
  { t: "Haz un haiku (Poema japonés de 3 frases).", pick: 1 },
  { t: "___ + ___ = ___", pick: 3 },
];

export const WHITE = [
  "La Celeste.",
  "¡Bizcochitos!",
  "Un zurdo de Humanidades tomando mate en el piso.",
  "Ir al almacén en chancletas y sin remera.",
  "Queso Colonia.",
  "Las cejas de Nacho Álvarez.",
  "Salir en la contratapa de El País con cara de haber dormido 2 horas.",
  "Una planilla de Excel de Presidencia que nadie pidió.",
  "Navidad sin vitel toné.",
  "Luis Suárez mordiendo la realidad.",
  "Hacer la peregrinación a la Virgen del Verdún en un Tesla.",
  "El Antel Arena.",
  "Caminar por 8 de Octubre a las 3 de la mañana.",
  "Robarse $100 de la alcancía del santo.",
  "¡Gol de Forlán en Sudáfrica!",
  "6 toneladas de merca que decomisó Prefectura.",
  "Un chape de tres.",
  "Un cumpleaños infantil en el Parque Rodó con viento polar.",
  "Los que todavía dicen que Peñarol es el manya del siglo.",
  "Suscribirse a Búsqueda.",
  "Turismo para ver carpinchos en Rocha.",
  "Señoras de Tienda Inglesa en bikini.",
  "Un decreto de Lacalle Pou. Obviamente.",
  "La persistencia del PIT-CNT.",
  "La herencia de Batlle.",
  "El autor intelectual de 'Soy celeste'.",
  "Una excursión no supervisada al COMCAR.",
  "Una película de Fede Álvarez filmada en Malvín.",
  "El arquitecto de Punta Carretas Shopping.",
  "Un beso de Yamandú Orsi.",
  "El Uruguay de antes, cuando el boleto salía dos pesos.",
  "El fan art erótico de los Fatales.",
  "Natalia Oreiro tocando cumbia en acordeón ruso.",
  "El galán vendedor de tortas fritas.",
  "La campaña de Carolina Cosse para arreglar una vereda.",
  "Azul FM explicando la grieta.",
  "Uniformes de túnica y moña.",
  "Karina Vignola en el Teatro de Verano.",
  "La verdad oculta de Artigas.",
  "El niño que vendía rifas para el viaje de egresados.",
  "El Chuy.",
  "Las familias del Sueño del Pibe.",
  "Meter una vaca en un Uber.",
  "La Narcopaloma de la rambla.",
  "Un hombre haciendo fila en el BPS.",
  "La ruta Interbalnearia en enero.",
  "La tía que defiende a Manini en la sobremesa.",
  "Trancadera en Bulevar Artigas.",
  "Abortar a tiempo un comité de base.",
  "Una nota de Subrayado.",
  "Una reproducción anatómicamente correcta de las nalgas de Natalia Oreiro.",
  "Carmen Barbieri lamiendo un alfajor Marley.",
  "La edición ilustrada de 'No era penal'.",
  "Sartori regalando promesas en una feria vecinal.",
  "Un grupo de gurises vapuleando a Gardelito.",
  "Masturbarse viendo a Petinatti.",
  "Un proyecto de fotografía en el Cilindro Municipal.",
  "Un ñeri de La Teja que se parece a Bruce Willis.",
  "Engrasar el cuerpo desnudo de Novick.",
  "Tener la hablada de Salle.",
  "Un cofre con la plata del Banco Pan de Azúcar.",
  "Dionisio Díaz.",
  "Un trofeo al mejor cebador de mate.",
  "Sendic cabalgando una tarjeta corporativa.",
  "Pedir PedidosYa en Cabo Polonio.",
  "Ir a Piriápolis a comer churros y volverse.",
  "Ir a Ciudad Vieja en hora pico.",
  "Un calendario de Pasión de Carnaval.",
  "Gustaf.",
  "¡Pero sólo chapamos una vez!",
  "Escuchar Rombai tomando colet.",
  "Romantizar al Canario Luna.",
  "Hacer chistes de Juana de Ibarbourou.",
  "La vez que salí en Día Perfecto.",
  "Noches de Nostalgia.",
  "Sacar un préstamo en el BROU para comprar yerba.",
  "Una foto de Mujica autografiada por Lacalle Pou.",
  "Dar dulce de leche con el dedo.",
  "Gritar 'bo' hasta que abran.",
  "El misterio de Berríos.",
  "El dulce sonido de OSE rompiendo la calle del frente.",
  "Sacarse restos de bizcocho de entre los dientes con una bombilla.",
  "Un desnudo autografiado de Jorge Drexler.",
  "Fantasías sexuales con el Loco Abreu.",
  "Pablo Mieres.",
  "Apretar en el Prado.",
  "Mónica Xavier.",
  "Masturbarse con Vick Vaporub.",
  "Cucharear a Mujica.",
  "#TemblorUY.",
  "Decir 'Feliz cumple, bo' cuando se canta cumpleaños.",
  "Decir 'pa, qué temazo' cuando suena La Vela Puerca.",
  "La Ámsterdam.",
  "El mejor episodio de Decalegrón.",
  "No Te Va Gustar en loop.",
  "INAU.",
  "Un problema de salud que hace que uno hable como Salle.",
  "Hacer cosplay del Bananero.",
  "El verdadero inventor del chivito.",
  "Casarse en Punta Carretas Shopping.",
  "La versión de Hollywood de El Lobizón.",
  "Andar como perro por la rambla.",
  "Hipoglós del Casmu.",
  "La panza de Lacalle Pou después de la Semana de la Cerveza.",
  "Andrade en posición fetal.",
  "Carrito de choripán frente al Centenario.",
  "José Mujica.",
  "Natalia Oreiro.",
  "Pagarle al cuidacoches en especies.",
  "Daniel Salinas.",
  "Pilsen®.",
  "Un puro bla bla de boliche.",
  "Estar endeudado hasta las cejas con la OCA.",
  "Bañarme en la fuente de Plaza Independencia.",
  "Conaprole... siempre con algo más caro.",
  "El hilo de Twitter de un politólogo uruguayo.",
  "3 bizcochos por $100.",
  "Vestirse de La Cumparsita con fines sexuales.",
  "La señora que baila sola en todos los tablados.",
  "Nervioso y con mate lavado.",
  "Cartas contra la Humanidad.",
  "Golpear gente en la calle.",
  "Enseñarle a un robot a amar.",
  "Contar una historia basura que no llega a ningún lado.",
  "Tirarse un pedo que viene con sorpresa.",
  "Pretender que sexo y género se pueden desvincular.",
  "Avisar que estoy por venirme.",
  "Lamer las cosas para reclamarlas como propias.",
  "Dar el 110%.",
  "Tener un paro cardiaco.",
  "Andar juzgándolo todo.",
  "Decir te amo.",
  "Que entren a robar tu casa y que violes a los ladrones.",
  "La única persona gay en cientos de kilómetros de distancia.",
  "Combustión Humana Espontánea.",
  "Fuerzas oscuras y misteriosas más allá de nuestro control.",
  "Resolver problemas con violencia.",
  "Tener la capacidad de hablar con los elefantes.",
  "Yodeling inapropiado.",
  "Fantasías con leñadores.",
  "COVID-19.",
  "A los hombres también nos matan.",
  "El Negro de WhatsApp.",
  "Destaquear infinitamente el water.",
  "Baygon.",
  "La Familia Tradicional.",
  "Progres®.",
  "Ultra conservador®.",
  "Hacerse la vístima.",
  "El Hampa organizada contra el barrio.",
  "Las lágrimas de Amber Heard.",
  "Un Hyundai Excel gris sin placas.",
  "Una huelga de mujeres taxistas.",
  "Excremento de unicornio.",
  "Un Trans bordador",
  "El Instituto Nacional del Hombre.",
  "Mi frágil masculinidad.",
  "Will Smith cacheteando a Putin.",
  "Un Yihadista.",
  "Audios de WhatsApp de 5 minutos.",
  "La misión feminista de eliminar penes.",
  "La Peste Negra",
  "Mi estado sentimental.",
  "Carbono Neutral®G",
  "La Ideología de Género.",
  "Traumas maternos.",
  "Traumas paternos.",
  "Eyaculación precoz.",
  "La amiga de mami que vende cremas.",
  "Tener sexo por primera vez.",
  "¡Batman!",
  "Peleas de almohadas sexys.",
  "Personas menstruantes.",
  "Tener vagina.",
  "Tener pene.",
  "Escapar a Suiza.",
  "Enfermedades de transmisión sexual.",
  "Privilegio negro.",
  "White Life Matters.",
  "Poner más gente blanca en el Comcar.",
  "Un huequito en la pared para espiar.",
  "El pene.",
  "Canestén oG",
  "Aedes Aegypti.",
  "Ponerle pasas al tamal.",
  "Bidets obligatorios en todas las casas.",
  "La vagina.",
  "Los dos aquí presentes que antes cogían.",
  "Pie de Atleta.",
  "Tu ansiedad y depresión.",
  "La leche.",
  "ESCRIBIR SIEMPRE EN MAYÚSCULAS.",
  "Peleas de gallos en la Asamblea Legislativa.",
  "Un teléfono público.",
  "¡Guaro, guaro!",
  "Hacer huelga por 2 meses.",
  "Una campaña feminista hecha por hombres.",
  "El Papa.",
  "El último bus del día.",
  "Divorcio Igualitario.",
  "Gente negra.",
  "Gente blanca.",
  "Indios.",
  "Chinos.",
  "Ver desnuda a mi abuela.",
  "Netflix and Chill",
  "Comer pollo en el bus.",
  "Elon Musk.",
  "George Soros.",
  "Bill Gates.",
  "Conseguir empleada en Tinder.",
  "Comerse las eses.",
  "La dosis #13 de la vacuna.",
  "Michael Jackson.",
  "MK Ultra.",
  "Johnny Depp.",
  "Pellizcarse el pene con un zipper.",
  "Filtro de belleza para hombres.",
  "Vender un riñón.",
  "Muestras gratuitas.",
  "Minorías.",
  "Derechos Humanos.",
  "Lenguaje Inclusivo.",
  "Descubrir que tus padres eran actores porno.",
  "El patriarcado.",
  "La gonorrea.",
  "Feministas rabiosas defecando mezquitas en Arabia Saudita.",
  "Justin Bieber.",
  "Hakunna Matata.",
  "Chicharrones.",
  "Tu mamá.",
  "Viajar a Marte sin retorno.",
  "No contribuir H la sociedad de ninguna manera.",
  "Destruir la evidencia.",
  "Un embarazo sorpresa.",
  "Semen de ballena.",
  "Hitler.",
  "El prepucio.",
  "Mi colección de perfiles falsos.",
  "Ser pobre pero tener un tele de 80 pulgadas.",
  "Brincarse las clases de religión para ir a fumar.",
  "Un indigente masturbándose en el bus.",
  "Hermanas de leche.",
  "Veganos.",
  "Sopa Maru Chan",
  "Una uña de pie en mi picadillo de papa.",
  "Pobres oyendo música clásica.",
  "Eyacular marshmallows.",
  "Llorar cuando suena Navidad Sin Tí.",
  "Pobres teniendo sixtillizos.",
  "Ser influencer.",
  "Mi control de esfínteres.",
  "Chorrear café en una media de fútbol.",
  "Llorar después de coger.",
  "Herpes labial.",
  "Leggings étnicas.",
  "Ir a un bar en chanclas.",
  "Racismo invertido.",
  "Un proyecto de ley que fomente la industria de los Maripepinos.",
  "Gente que no coje.",
  "Millennials.",
  "Pagarle al abuelo con criptomonedas.",
  "Teorías de Conspiración.",
  "Hacer lo correcto.",
  "El agujero negro.",
  "El Corán.",
  "“¿Vos no sabe quién soy yo?”",
  "Sacrificios humanos indígenas.",
  "Alcanzar el Nirvana",
  "Chocar con el tren.",
  "Burlarse de Mahoma.",
  "Buda.",
  "Monges tibetanos.",
  "Pésimas decisiones de vida.",
  "Siliconas asimétricas.",
  "Arroz con leche materna.",
  "La llegada de la pizza.",
  "El Ku Klux Klan.",
  "Múltiples puñaladas.",
  "1000 likes instantáneos.",
  "Los Amish.",
  "Un mimo teniendo un derrame.",
  "Tensión sexual.",
  "Experimentar con medicamentos en el tercer mundo.",
  "Hambruna.",
  "Fusil de asalto AK-47.",
  "Los ritmos del África.",
  "Un congelador lleno de órganos.",
  "Hombres que se creen mujeres.",
  "Daño colateral.",
  "Gordofobia.",
  "La placenta.",
  "Armas químicas.",
  "Yo.",
  "Fricción.",
  "Papá Noel.",
  "El silencio.",
  "Un chino turista que quiere algo pero tristemente no puede comunicarlo.",
  "Lo lamentamos, este contenido no puede ser visto en su región.",
  "Problemas íntimos.",
  "Un call center en la India.",
  "Lechuga caliente.",
  "El orgasmo femenino.",
  "Un león comiéndose a un especista.",
  "Trans Scouts.",
  "¡Sexo sorpresa!",
  "Lanzar una virgen al volcán.",
  "Amputados.",
  "Pedófilos.",
  "Caníbales.",
  "El Lobby LGBTIQ+",
  "Amigos con derechos.",
  "Atracar un banco de esperma.",
  "Morir.",
  "Teorías de conspiración.",
  "La gran depresión.",
  "La supervivencia del más fuerte.",
  "Mi alma.",
  "Nazis",
  "El festival de Salchichas.",
  "La vacunación forzosa.",
  "Los pedófilos reclamando derechos.",
  "Una erección espontánea.",
  "Tener vejiga hiperactiva.",
  "La ventana de Overton.",
  "La manipulación mediática.",
  "Amputación genital.",
  "Promiscuos repartiendo SIDA.",
  "La bandera del orgullo heterosexual.",
  "El libro de Mormón.",
  "Shakira.",
  "Alguien transedad.",
  "Mujeres con próstata.",
  "La teoría de la evolución.",
  "Izquierditas impulsando farmacéuticas.",
  "El orgullo gay.",
  "A paguitos de polaco.",
  "Las que piensan que el violador eres tú.",
  "Lo que me empatriarca.",
  "La disforia de género.",
  "Mi asesinato, mi desición.",
  "Vacunas que matan niños.",
  "Un pansexual.",
  "La plandemia.",
  "Una persona de género espejo viéndose al espejo.",
  "La agenda de despoblación mundial.",
  "Un niño y una niña adoptando a un gay.",
  "Ser un ateo obsesionado con Dios.",
  "La élite.",
  "Un mono que se autopercibe hombre.",
  "La campaña del miedo",
  "Los Masones.",
  "Donald Trump.",
  "Greta Trunberg.",
  "La lealtad de Jada Pinkett.",
  "La píldora roja.",
  "Keanu Reeves.",
  "Un queer musulmán.",
  "Chuck Norris",
  "Pizza Gate.",
  "Estrógeno.",
  "Dos gordas bloqueando el paso en el bus.",
  "Terraplanistas.",
  "Olor a gente vieja.",
  "Joe Biden.",
  "Osama Bin Laden.",
  "Tom Cruise.",
  "50.000 voltios directo a los pezones.",
  "Los efectos especiales de Bollywood.",
  "Goku.",
  "Lady Gaga.",
  "Decencia humana básica.",
  "Made in China.",
  "Ucrania.",
  "Mr. Bean.",
  "Las Kardashian.",
  "Messi.",
  "Brad Pitt.",
  "Tensión sexual.",
  "Gal Gadot.",
  "Tom Holland.",
  "Tokyo.",
  "Ser un indigente.",
  "El clítoris.",
  "El arte de la seducción.",
  "Las semillas del ermitaño.",
  "Mi machete.",
  "Envidiar el pene.",
  "Otakus.",
  "Muslos poderosos.",
  "Volverse musulmán.",
  "Negrear",
  "Ricky Martin.",
  "Mi vida sexual.",
  "Un flujo infinito de diarrea.",
  "Miley Cyrus.",
  "Es por vos.",
  "Disfunción erectil.",
  "Bananos.",
  "Tirarse un pedo y huir.",
  "La ignorancia.",
  "La insondable estupidez.",
  "Hacer caca en una laptop y cerrarla.",
  "Limpieza étnica.",
  "La maldad humana.",
  "Picazón en el trasero.",
  "Caca que arde.",
  "Una paradoja de viajar en el tiempo.",
  "El pasado.",
  "Pañales con caca.",
  "La ceguera.",
  "Una vagina que lleva a otra dimensión.",
  "Un condón defectuoso.",
  "Una horda de zombis.",
  "Beber del water y comer basura.",
  "El mismísimo diablo.",
  "Blanqueamiento anal.",
  "Heteronormatividad.",
  "Un granero lleno de cadáveres.",
  "Quedarse virgen.",
  "Tener amigos.",
  "Falsos dioses.",
  "Un pelo púbico desviado.",
  "Hormonización infantil.",
  "El imaginario colectivo.",
  "Histeria colectiva.",
  "Huevos.",
  "Empanadas arregladas.",
  "El rito de apareamiento",
  "El Big Bang.",
  "Condones de sabores.",
  "Piercings genitales.",
  "Autocanibalismo.",
  "El síndrome de estocolmo.",
  "Pezones parados.",
  "Comer hasta vomitar.",
  "Un micropene.",
  "Obesidad.",
  "Esta post moderna respuesta.",
  "Mis genitales.",
  "Torsión testicular.",
  "Sus mentiras.",
  "Whiskas Premium®.",
  "Oompa Loompas.",
  "Cachorritos.",
  "Sentir miedo de ti mismo.",
  "Limpiarle el trasero.",
  "El Nuevo Orden Mundial.",
  "Labios vaginales enormes.",
  "Una vida de tristeza.",
  "El despecho.",
  "Asaltacunas.",
  "Asaltar Tumbas.",
  "Ponerse la ropa interior al revés para no tener que lavarla.",
  "Ahorcar el ganzo.",
  "Torturas infrahumanas.",
  "La burocracia insoportable.",
  "Una tortuga mordiendo la punta de tu pene.",
  "La estupidez humana.",
  "Hombres que no vuelven a llamar.",
  "Tocamientos genitales.",
  "Esperar hasta el matrimonio.",
  "Natalie Portman",
  "Bromas sobre Hitler en un momento inoportuno.",
  "Los gays.",
  "Fans de BTS.",
  "Tener arena en la vagina.",
  "Una fiesta de cumpleaños decepcionante.",
  "Propaganda homosexual.",
  "Alienígenas ancestrales.",
  "Practicar la abstinencia.",
  "Ser atacado por un dinosaurio.",
  "Calentamiento global.",
  "Despertar medio desnudo en el parqueo de McDonalds.",
  "Guiñarle el ojo a viejitos.",
  "Paris Hilton.",
  "Bond James Bond.",
  "Fatalities.",
  "Manos de pianista.",
  "Kanye West.",
  "La pubertad.",
  "La agricultura.",
  "Trolls.",
  "Alcoholismo.",
  "Dinámicas grupales.",
  "Preguntas de selección basadas en la raza.",
  "La lluvia dorada.",
  "Comer Nutella H cucharadas.",
  "Hacer pucheros.",
  "La Esclavitud.",
  "Martin Luther King Jr.",
  "Fantasmas.",
  "La selección Natural",
  "El sufragio femenino.",
  "Pasivo agresividad.",
  "Echar marcha atrás.",
  "Las emociones.",
  "Tiempo a solas.",
  "Viagra®.",
  "Ser rico.",
  "Una pistola de agua llena de orines de gato.",
  "Ser fabuloso.",
  "Arnold Schwarzenegger.",
  "Rambo.",
  "Terminator.",
  "Darth Vader.",
  "Helado oscuro.",
  "Asíaticos con pobre desempeño en matemáticas.",
  "Rascarse el trasero a escondidas.",
  "Miedo a los desconocidos.",
  "Una erección que dura 4 horas.",
  "Llegar a tercera base.",
  "Bombas caseras.",
  "Abdominales espectaculares.",
  "Sexo con señoras gordas.",
  "Un relato erótico de Harry Potter.",
  "Música turbo folk de Europa del Este.",
  "Hacerse caca en los pantalones.",
  "La fuerza.",
  "Ancianos japoneses.",
];
