// Mazo original de "Cartas vs los Pibes" — contenido propio, con onda uruguaya.
// Cartas negras: { t: "texto con ___", pick: cuántas blancas se juegan }
// Cartas blancas: strings.

export const BLACK = [
  { t: "Lo que arruinó el asado familiar fue ___.", pick: 1 },
  { t: "Mi terapeuta se quedó sin palabras cuando le conté lo de ___.", pick: 1 },
  { t: "En Uruguay no hay nada más sagrado que ___.", pick: 1 },
  { t: "El nuevo plan del gobierno para bajar la inflación es ___.", pick: 1 },
  { t: "___. Transmite en exclusiva Tenfield.", pick: 1 },
  { t: "Perdí a la mitad de mis amigos por culpa de ___.", pick: 1 },
  { t: "¿Qué tengo escondido abajo del colchón?", pick: 1 },
  { t: "El verdadero secreto de Luis Suárez es ___.", pick: 1 },
  { t: "Lo único que une a Peñarol y Nacional es ___.", pick: 1 },
  { t: "Nueva campaña de turismo: 'Visitá Punta del Este y llevate ___'.", pick: 1 },
  { t: "___ más ___: la receta del peor lunes de mi vida.", pick: 2 },
  { t: "Mi vieja encontró ___ revisándome la pieza.", pick: 1 },
  { t: "Este fin de año brindo por ___.", pick: 1 },
  { t: "El verdadero motivo del corte de UTE fue ___.", pick: 1 },
  { t: "Lo que más extraño del Uruguay de antes es ___.", pick: 1 },
  { t: "La abuela bendice la mesa y da gracias por ___.", pick: 1 },
  { t: "El próximo presidente prometió ___ para todos.", pick: 1 },
  { t: "¿Qué me hace llorar arriba del bondi?", pick: 1 },
  { t: "La murga de este año se llama 'Los ___'.", pick: 1 },
  { t: "En la rambla, a las seis de la mañana, me crucé con ___.", pick: 1 },
  { t: "Lo que ningún uruguayo va a admitir es que le encanta ___.", pick: 1 },
  { t: "El olor del Cerro es una mezcla de ___ y ___.", pick: 2 },
  { t: "Para sobrevivir al invierno montevideano necesitás ___.", pick: 1 },
  { t: "Le pedí a la Virgen de Verdún por ___.", pick: 1 },
  { t: "Nuevo sabor de Conaprole: ___.", pick: 1 },
  { t: "Mi cita de Tinder se borró cuando vio ___.", pick: 1 },
  { t: "Hoy en el informativo: ___ provoca caos en 18 de Julio.", pick: 1 },
  { t: "___: el regalo perfecto para el Día del Padre.", pick: 1 },
  { t: "Renuncié al laburo para dedicarme de lleno a ___.", pick: 1 },
  { t: "El asado se arruinó porque alguien trajo ___.", pick: 1 },
  { t: "Mi último deseo antes de morir es ___.", pick: 1 },
  { t: "La nueva atracción del parque Rodó es ___.", pick: 1 },
  { t: "¿Por qué no puedo dormir de noche?", pick: 1 },
  { t: "Lo que de verdad pasa en el vestuario de la Celeste es ___.", pick: 1 },
  { t: "Aprendí a la mala que no se mezcla ___ con ___.", pick: 2 },
  { t: "El grupo de WhatsApp de la familia explotó por ___.", pick: 1 },
  { t: "Mi superpoder secreto es ___.", pick: 1 },
  { t: "En el carnaval más largo del mundo no puede faltar ___.", pick: 1 },
  { t: "Cuando sea millonario voy a comprar ___.", pick: 1 },
  { t: "El cura me dijo que rezara tres Padrenuestros por ___.", pick: 1 },
  { t: "La verdadera causa del cambio climático es ___.", pick: 1 },
  { t: "Lo que encontré en la heladera a las tres de la mañana fue ___.", pick: 1 },
  { t: "Mi nuevo emprendimiento es vender ___ en la feria de Tristán Narvaja.", pick: 1 },
  { t: "El examen de manejo lo reprobé por ___.", pick: 1 },
  { t: "Lo que arruina cualquier primera cita es ___.", pick: 1 },
  { t: "Señoras y señores, con ustedes: ___ en vivo desde el Teatro de Verano.", pick: 1 },
  { t: "El motivo de mi crisis existencial de esta semana es ___.", pick: 1 },
  { t: "Lo que me regalaron en el amigo invisible fue ___.", pick: 1 },
];

export const WHITE = [
  "Un mate lavado",
  "La garra charrúa",
  "Luis Suárez pegando un mordisco",
  "Un asado que tarda cuatro horas",
  "El bondi que nunca llega",
  "Natalia Oreiro cantando el himno",
  "Pepe Mujica filosofando en la chacra",
  "Lacalle Pou sin remera en la playa",
  "Yamandú Orsi mirándote fijo",
  "Un chivito canadiense con todo",
  "El wifi de ANTEL en hora pico",
  "Un corte de UTE en pleno verano",
  "El agua de OSE con gusto a cloro",
  "La murga a las tres de la mañana",
  "Peñarol perdiendo el clásico",
  "Nacional saliendo campeón de penal",
  "Tenfield y sus derechos de televisión",
  "Una torta frita bajo la lluvia",
  "Punta del Este lleno de argentinos en enero",
  "Un balneario fantasma en invierno",
  "Dulce de leche por cucharadas",
  "Una bombilla tapada",
  "El precio de la nafta",
  "Hacer la cola en el Abitab",
  "El viento de Montevideo doblándote el paraguas",
  "La rambla un domingo gris",
  "El gol de Ghiggia en el Maracaná",
  "El Maestro Tabárez explicando la vida",
  "Una garrafa de supergas vacía un domingo",
  "El semáforo eterno de 18 de Julio",
  "La libreta de conducir que nunca apruebo",
  "Un cuarto y mitad de mortadela",
  "Garra, corazón y poco fútbol",
  "El olor a frigorífico",
  "Una crisis existencial a las cuatro de la mañana",
  "Llorar en el baño de una fiesta",
  "Mandar un audio de nueve minutos",
  "Mi terapeuta rindiéndose",
  "El grupo de WhatsApp de la familia",
  "Adoptar una postura política en el asado",
  "Fingir mi propia muerte para no ir a un cumpleaños",
  "Un ataque de pánico en el súper",
  "La inevitabilidad de la muerte",
  "Bloquear a mi ex y desbloquearlo cinco veces",
  "El último pedazo de pizza",
  "Una deuda impagable",
  "Stalkear perfiles a las dos de la mañana",
  "Pegar un grito sin saber por qué",
  "El botón de snooze",
  "Mi niño interior llorando",
  "Una verdad incómoda en la cena de Navidad",
  "Tirarme un pedo y echarle la culpa al perro",
  "Quedarme dormido en una reunión de Zoom",
  "Comer milanesas tres días seguidos",
  "Un tupperware con algo del mes pasado",
  "La factura de la tarjeta después de las fiestas",
  "Prometer que voy al gimnasio el lunes",
  "Hablar solo en la ducha",
  "Una bandeja de bizcochos a las siete de la mañana",
  "El placard que se cae cuando lo abrís",
  "Discutir con un desconocido en internet",
  "Mi historial de búsqueda",
  "Un domingo de lluvia sin nada para hacer",
  "El mate amargo del compañero de laburo",
  "Una empanada que te quema el paladar",
  "El olor a ropa mojada que no se secó",
  "Fingir que entiendo de vinos",
  "Un asado vegetariano",
  "Pedir delivery para uno solo y comer como tres",
  "La cuenta del cumpleaños dividida en partes iguales",
  "Una siesta de tres horas que arruina la noche",
  "El primo que trae la guitarra al asado",
  "Cantar el himno sin saber la letra",
  "Un perro que ladra toda la madrugada",
  "El sonido del despertador un lunes",
  "Mi autoestima después de leer los comentarios",
  "Un cumpleaños infantil con animador",
  "El tío que arregla el país en la sobremesa",
  "Una factura de luz que no entiendo",
  "El olor del ómnibus en verano",
  "Un mensaje visto y no contestado",
  "Llorar viendo una publicidad",
  "El miedo a quedarme solo",
  "La cuota del gimnasio que pago y no uso",
  "Una resaca de tres días",
  "El dedo del pie contra la pata de la cama",
  "Comer algo del piso usando la regla de los cinco segundos",
  "La presión de tener todo resuelto a los treinta",
  "Un grupo de turistas sacándose fotos en el medio de la vereda",
  "Mi cuenta bancaria a fin de mes",
  "La gente que aplaude cuando aterriza el avión",
  "Una factura de la mutualista",
  "El silencio incómodo en el ascensor",
  "Confundir a alguien y saludarlo igual",
  "Reírme en el momento menos apropiado",
  "El olor a nafta que secretamente me gusta",
  "Un parrillero que no presta las pinzas",
  "Hervir el mate sin querer",
  "El zorrillo que se metió abajo del rancho",
  "Una invitación a una venta de Tupperware",
  "La señora que se cuela en la cola del Abitab",
  "Llegar tarde y echarle la culpa al tránsito",
  "El verano con 38 grados y sin aire",
  "Un grupo de la facultad que no hace nada",
  "Cobrar en pesos y llorar en dólares",
  "El changuito del súper con una rueda trabada",
  "Una promesa de campaña",
  "El último que se va apaga la luz",
  "Mi vida amorosa",
  "Una pregunta capciosa de mi suegra",
  "El cuñado que sabe de todo",
  "Pisar descalzo un Lego",
];
